# Generated by Django 5.2.13 on 2026-04-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('specialization', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
